/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AppointmentRequest = IDL.Record({
  'id' : Time,
  'name' : IDL.Text,
  'preferredDateTime' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'departmentService' : IDL.Text,
  'timestamp' : Time,
  'contactDetails' : IDL.Text,
});
export const Contact = IDL.Record({
  'id' : Time,
  'contactInfo' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DomainDraft = IDL.Record({
  'content' : IDL.Text,
  'lastSaved' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(AppointmentRequest)], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], []),
  'getAppointmentById' : IDL.Func([Time], [AppointmentRequest], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactById' : IDL.Func([Time], [Contact], []),
  'getDomainDraft' : IDL.Func([], [IDL.Opt(DomainDraft)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDomainDraft' : IDL.Func([IDL.Text], [], []),
  'submitAppointmentRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'toggleDecommissionMode' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AppointmentRequest = IDL.Record({
    'id' : Time,
    'name' : IDL.Text,
    'preferredDateTime' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'departmentService' : IDL.Text,
    'timestamp' : Time,
    'contactDetails' : IDL.Text,
  });
  const Contact = IDL.Record({
    'id' : Time,
    'contactInfo' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DomainDraft = IDL.Record({ 'content' : IDL.Text, 'lastSaved' : Time });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(AppointmentRequest)], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], []),
    'getAppointmentById' : IDL.Func([Time], [AppointmentRequest], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactById' : IDL.Func([Time], [Contact], []),
    'getDomainDraft' : IDL.Func([], [IDL.Opt(DomainDraft)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDomainDraft' : IDL.Func([IDL.Text], [], []),
    'submitAppointmentRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'toggleDecommissionMode' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };