/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppointmentRequest {
  'id' : Time,
  'name' : string,
  'preferredDateTime' : string,
  'notes' : [] | [string],
  'departmentService' : string,
  'timestamp' : Time,
  'contactDetails' : string,
}
export interface Contact {
  'id' : Time,
  'contactInfo' : string,
  'subject' : string,
  'name' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface DomainDraft { 'content' : string, 'lastSaved' : Time }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<AppointmentRequest>>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getAppointmentById' : ActorMethod<[Time], AppointmentRequest>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactById' : ActorMethod<[Time], Contact>,
  'getDomainDraft' : ActorMethod<[], [] | [DomainDraft]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDomainDraft' : ActorMethod<[string], undefined>,
  'submitAppointmentRequest' : ActorMethod<
    [string, string, string, string, [] | [string]],
    undefined
  >,
  'submitContact' : ActorMethod<[string, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];